local pc = require("computer") 
local sh = require("shell")
local term = require("term")
local os = require("os")
  sh.execute("/home/security.lua")
  term.clear()
  print("Security System | ERROR")
  print("----------------------------------------------------------------------------------------------------------------------------------------------------------------")
  print("Error: interputted")
  os.sleep(2)
  pc.shutdown()
